services:
  mi-mongo-dc:
    container_name: mi-mongo-compose
    image: mongo
    networks:
      - mi-red-compose
    volumes:
      - mi-volumen-compose:/data/db
    stdin_open: true
    tty: true

  mi-mongo-express-dc:
    container_name: mi-mongo-express-compose
    image: mongo-express
    networks:
      - mi-red-compose
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo-compose
    stdin_open: true
    tty: true

networks:
  mi-red-compose:

volumes:
  mi-volumen-compose:
